# Generated by Django 5.0.6 on 2024-07-01 14:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_acessorio"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="acessorio",
            options={"ordering": ["descricao"], "verbose_name": "Acessorio", "verbose_name_plural": "Acessorios"},
        ),
    ]
